name: Deploypara o Vercel 
on: 
  push: 
    branches:
      - main 
jobs:
  Deploy-to-production:    
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Estagio 1
        run: echo "hello word"
        
        
      - name: Estagio 2 - Instala o CLI do vercel
        run: npm install --global vercel@latest 
        
      
      - name: Estagio 3 - Pull Vercel token 
        run: vercel pull --yes -- environment=production --token=${{ secrets.TESTE }}
      
      - name: Estagio 4 - Construir o projeto 
        run: vercel build -- prod -- token=${{ secrets.TESTE }}    
        
      - name: Estagio 5 - Enviar o Projeto para o Vercel 
        run: vercel deploy --prebuilt --prod --token=${{ secrets.TESTE }}
        
